# This workflow runs the typescript implementation unit tests
name: release
on:
  release:
    types: [published]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: REF="${{ github.ref }}" ./ci/release.sh
